### ISSUE TITLE
Some API params should be defined as optional

### ISSUE THREAD

**Issue by latica-jp** [kintone/dts-gen#130]
Hi,

Some params on kintone API are defined as optional.

Besides, some of these params doesn't seem to be defined as optional in the type definition file, so TS compiler complains when we omit these params.

For example,

```
   namespace plugin {
        namespace app {
            function getConfig(pluginId: string): any;
            function setConfig(
                config: any,
                callback: () => void // should be optional?
            ): void;
```

I believe that `callback` should be optional in this case.

**Comment by koba04** [comment]
@latica-jp 
Thank you!
You are right. The type should be optional.
We'll fix the issue and investigate whether there is any type issues or not.
Of course, PRs are also welcome! 😄

**Comment by yokotaso** [comment]
@koba04 Is this issue alredy fixed?

**Comment by koba04** [comment]
@yokotaso Thank you! Yeah, it has been already fixed!

https://github.com/kintone/dts-gen/blob/master/kintone.d.ts#L181

@latica-jp This has been fixed at the latest release so I'll close this. Thank you for your report 👏👏👏
