### ISSUE TITLE
disabled field is missing in generated field type definition

### ISSUE THREAD

**Issue by yokotaso** [kintone/dts-gen#23]
When user want to disable field to write, `record.field.disabled = true;`

But generated type definition is not generated.

https://developer.cybozu.io/hc/ja/articles/200306919-%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB%E3%83%89%E3%81%AE%E5%85%A5%E5%8A%9B%E4%B8%8D%E5%8F%AF%E3%82%92%E3%83%9C%E3%82%BF%E3%83%B3%E3%81%A7%E5%AE%8C%E5%85%A8%E5%88%B6%E5%BE%A1-

**Comment by koba04** [comment]
Fixed vis #111
