### ISSUE TITLE
Fix type definition or api reference

### ISSUE THREAD

**Issue by Climber22** [kintone/dts-gen#69]
Thanks for this great library!

I've found one mistake at this line.
https://github.com/kintone/dts-gen/blob/a7be6d4d56ba7d23e5de989ebad02e8ecca2c543/kintone.d.ts#L9

According to [official site](https://developer.cybozu.io/hc/ja/articles/202166310)
![スクリーンショット 2019-06-02 22 38 19](https://user-images.githubusercontent.com/25131938/58762103-2a674180-8587-11e9-9f6d-966239e4f422.png)

The `kintone.api.url` function must accept 2 arguments.
Or api reference itself is wrong ...?

I'm not sure which is true, so I'm happy if you give me some advice.

**Comment by koba04** [comment]
@Climber22 
Thank you for reporting this!! 🎉 
We'll look into this! 👀

**Comment by koba04** [comment]
@Climber22 
I think it's a bug so we have to fix it.
Please send a PR if you want 🚀 
We really appreciate it 😄

**Comment by Climber22** [comment]
Thanks for investigation!
I'll make PR 👍

**Comment by koba04** [comment]
Thank you! 🙏
